project:
  type: book
  output-dir: docs

book:
  title: "Cours_Tests_statistiques"
  author: "Quentin Laval"
  date: "15/01/2026"
  chapters:
    - index.qmd
    - 1_stat_test.qmd
    - 2_multiple_testing.qmd
    - 3_power_and_nsn.qmd
    - 4_conclusion.qmd
    - 5_references.qmd

bibliography: references.bib

format:
  html:
    theme:
      - cosmo
      - brand
    embed-resources: true
  pdf:
    documentclass: scrreprt

editor: visual

